
pages:
  - Home: 'index.md'
  - Titanium:
    - Home: 'Titanium/index.md'
    - Skeleton: 'Titanium/Skeleton.md'
    - Modules:
      - Base:
        - Base: 'Titanium/Modules/Base/index.md'
      - Cassandra:
        - Cassandra: 'Titanium/Modules/Cassandra/index.md'
      - Commodore:
        - Commodore: 'Titanium/Modules/Commodore/index.md'
      - Corporis:
        - Corporis: 'Titanium/Modules/Corporis/index.md'
      - Perplex:
        - Perplex: 'Titanium/Modules/Perplex/index.md'
      - Nucleus:
        - Nucleus: 'Titanium/Modules/Nucleus/index.md'
  - MatterOverdrive:
    - Home: 'MatterOverdrive/index.md'
    - API:
      - API: 'MatterOverdrive/API/index.md'
    - Blocks:
      - Machines:
        - Inscriber: 'MatterOverdrive/Blocks/Machines/Inscriber.md'
      - Storage:
        - Titanium Crate: 'MatterOverdrive/Blocks/Storage/TitaniumCrate.md'
    - Items:
      - Tools:
        - Battery: 'MatterOverdrive/Items/Tools/Battery.md'
      - Armour:
        - Space Suit: 'MatterOverdrive/Items/Armour/SpaceSuit.md'
  - Electrodynamics:
    - Home: 'Electrodynamics/index.md'
  - GSuite:
    - Home: 'GSuite/index.md'



# Do not edit below here unless you know what you are doing!

theme_dir: 'material'
site_name: Horizon Mod Wikis
copyright: Horizon Studio 2018

repo_url: 'https://github.com/HrznStudio/Documentation'
repo_name: 'Contribute to this wiki'
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
theme:
  name: 'material'
extra:
  palette:
    primary: 'hrzn-black'
    accent: 'hrzn-white'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'assets/HrznStudio_avatar.png'
  feature:
    tabs: true
  direction: 'ltr'
  favicon: 'assets/HrznStudio_avatar.png'
  social:
    - type: 'github'
      link: 'https://github.com/HrznStudio'
    - type: 'twitter'
      link: 'https://twitter.com/HrznStudio'